# Generated by Django 4.2.27 on 2026-02-11 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team5', '0003_team5recommendationfeedback'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='team5city',
            new_name='team5_team5_city_na_2559f4_idx',
            old_name='team5_team5c_city_na_f57158_idx',
        ),
        migrations.RenameIndex(
            model_name='team5media',
            new_name='team5_team5_place_i_aec6fd_idx',
            old_name='team5_team5m_place_i_ee7274_idx',
        ),
        migrations.RenameIndex(
            model_name='team5mediarating',
            new_name='team5_team5_user_id_b4ccee_idx',
            old_name='team5_team5_user_id_2528c1_idx',
        ),
        migrations.RenameIndex(
            model_name='team5mediarating',
            new_name='team5_team5_media_i_d9079e_idx',
            old_name='team5_team5_media_i_e8b9b9_idx',
        ),
        migrations.RenameIndex(
            model_name='team5place',
            new_name='team5_team5_city_id_66f1c5_idx',
            old_name='team5_team5p_city_id_4b6dfd_idx',
        ),
        migrations.RenameIndex(
            model_name='team5recommendationfeedback',
            new_name='team5_team5_user_id_b32221_idx',
            old_name='t5_fb_user_action_created_idx',
        ),
    ]
