# Generated by Django 4.2.27 on 2026-02-11 20:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LocationContext",
            fields=[
                (
                    "location_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.CharField(db_index=True, max_length=50)),
                (
                    "location",
                    models.CharField(
                        help_text="e.g., POINT(51.3890 35.6892)", max_length=100
                    ),
                ),
                ("radius_km", models.FloatField(default=100.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "location_context",
            },
        ),
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "recommendation_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.CharField(db_index=True, max_length=50)),
                ("item_id", models.CharField(db_index=True, max_length=50)),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("article", "Article"),
                            ("place", "Place"),
                            ("event", "Event"),
                            ("route", "Route"),
                        ],
                        max_length=20,
                    ),
                ),
                ("score", models.FloatField()),
                (
                    "reason_type",
                    models.CharField(
                        choices=[
                            ("interest", "Interest"),
                            ("location", "Location"),
                            ("popularity", "Popularity"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reason_description", models.TextField(blank=True)),
                (
                    "user_feedback",
                    models.CharField(
                        blank=True,
                        choices=[("like", "Like"), ("dislike", "Dislike")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("feedback_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "recommendations",
            },
        ),
        migrations.CreateModel(
            name="UserInteraction",
            fields=[
                (
                    "interaction_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.CharField(db_index=True, max_length=50)),
                ("item_id", models.CharField(db_index=True, max_length=50)),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("article", "Article"),
                            ("place", "Place"),
                            ("event", "Event"),
                            ("route", "Route"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[("view", "View"), ("like", "Like"), ("rate", "Rate")],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "user_interactions",
            },
        ),
        migrations.CreateModel(
            name="UserProfileFeature",
            fields=[
                (
                    "feature_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.CharField(db_index=True, max_length=50)),
                ("category", models.CharField(max_length=100)),
                ("weight", models.FloatField(default=0.0)),
                (
                    "source",
                    models.CharField(
                        choices=[("manual", "Manual"), ("interaction", "Interaction")],
                        max_length=20,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "user_profile_features",
            },
        ),
    ]
