"""Initial schema

Revision ID: ec3ff9d1ef7d
Revises: 
Create Date: 2026-02-12 10:58:52.199621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec3ff9d1ef7d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_moderation',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('media_ref_id', sa.UUID(), nullable=False),
    sa.Column('is_safe', sa.Boolean(), nullable=True),
    sa.Column('nsfw_score', sa.Float(), nullable=True),
    sa.Column('safe_score', sa.Float(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='analysis_status'), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_moderation_media_ref_id'), 'image_moderation', ['media_ref_id'], unique=False)
    op.create_index(op.f('ix_image_moderation_status'), 'image_moderation', ['status'], unique=False)
    op.create_table('image_tagging',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('media_ref_id', sa.UUID(), nullable=False),
    sa.Column('detected_place', sa.String(length=100), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='analysis_status'), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_tagging_media_ref_id'), 'image_tagging', ['media_ref_id'], unique=False)
    op.create_index(op.f('ix_image_tagging_status'), 'image_tagging', ['status'], unique=False)
    op.create_table('place_summaries',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('place_ref_id', sa.BigInteger(), nullable=False),
    sa.Column('overall_sentiment', sa.String(length=20), nullable=True),
    sa.Column('summary_liked', sa.Text(), nullable=True),
    sa.Column('summary_disliked', sa.Text(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='analysis_status'), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_place_summaries_place_ref_id'), 'place_summaries', ['place_ref_id'], unique=False)
    op.create_index(op.f('ix_place_summaries_status'), 'place_summaries', ['status'], unique=False)
    op.create_table('text_moderation',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('post_ref_id', sa.BigInteger(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('score_clean', sa.Float(), nullable=True),
    sa.Column('score_spam', sa.Float(), nullable=True),
    sa.Column('score_hate', sa.Float(), nullable=True),
    sa.Column('score_sexual', sa.Float(), nullable=True),
    sa.Column('score_violent', sa.Float(), nullable=True),
    sa.Column('score_insult', sa.Float(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='analysis_status'), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_text_moderation_post_ref_id'), 'text_moderation', ['post_ref_id'], unique=False)
    op.create_index(op.f('ix_text_moderation_status'), 'text_moderation', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_text_moderation_status'), table_name='text_moderation')
    op.drop_index(op.f('ix_text_moderation_post_ref_id'), table_name='text_moderation')
    op.drop_table('text_moderation')
    op.drop_index(op.f('ix_place_summaries_status'), table_name='place_summaries')
    op.drop_index(op.f('ix_place_summaries_place_ref_id'), table_name='place_summaries')
    op.drop_table('place_summaries')
    op.drop_index(op.f('ix_image_tagging_status'), table_name='image_tagging')
    op.drop_index(op.f('ix_image_tagging_media_ref_id'), table_name='image_tagging')
    op.drop_table('image_tagging')
    op.drop_index(op.f('ix_image_moderation_status'), table_name='image_moderation')
    op.drop_index(op.f('ix_image_moderation_media_ref_id'), table_name='image_moderation')
    op.drop_table('image_moderation')
    # ### end Alembic commands ###
